name: 'Update the image digest'

on:
  workflow_call:
    secrets:
      token:
        description: 'github token'
        required: true
      webhook:
        description: 'slack webhook'
        required: false

jobs:
  digest-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 #v6.0.1
        with:
          persist-credentials: false

      - run: |
          echo "DT=$(date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
          echo "B=$(date '+%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      - uses: navikt/digestabot@6c419f9c92ce6a841d25d44e1f91ae8d371ecdd3 #v1.1
        id: digestabot
        with:
          token: ${{ secrets.token }}
          team: teameresept
          labels-for-pr: 'automated pr, image digest update, automerge'
          branch-for-pr: 'image-digest-update-${{ env.B }}'
          title-for-pr: 'Update image digest at ${{ env.DT }}'
          description-for-pr: 'Update of image digest'
          commit-message: 'Update of image digest at ${{ env.DT }} [ci skip]'

      - name: merge
        if: ${{ steps.digestabot.outputs.pull_request_number != '' }}
        run: gh pr merge --auto --squash --delete-branch "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/pull/${{ steps.digestabot.outputs.pull_request_number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: report to slack
        if: success()
        uses: navikt/eresept-actions/slack-notify@main
        with:
          status: "${{ job.status }}"
          username: "digestabot ${{ github.event.repository.name }}"
          icon: ":github2:"
          title-success: "Merged PR #${{ steps.digestabot.outputs.pull_request_number }} _*${{ github.event.repository.name }}*_"
          message-success: "Changed files:\n```${{ steps.digestabot.outputs.changed_files }}```"
          webhook: ${{ secrets.webhook }}
