name: Snyk test, re-usable

on:
  workflow_call:
    inputs:
      threshold:
        description: 'severity threshold, default high'
        type: string
        required: false
        default: 'high'
      channel:
        description: 'slack channel'
        required: false
        type: string
        default: 'eresept'
      footer:
        description: 'slack footer'
        required: false
        type: string
        default: 'eresept Â© 2022'
    secrets:
      snyk-token:
        required: true
      token:
        description: 'github token'
        required: true
      webhook:
        description: 'slack webhook'
        required: true

jobs:
  snyk-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 #v6.0.1
        with:
          persist-credentials: false

      - name: create settings.xml
        uses: whelk-io/maven-settings-xml-action@9dc09b23833fa9aa7f27b63db287951856f3433d #v22
        with:
          repositories: '[{ "id": "eresept-parent", "name": "github", "url": "https://maven.pkg.github.com/navikt/eresept-parent", "releases": { "enabled": "true" }, "snapshots": { "enabled": "false" } }, { "id": "xerces", "name": "github", "url": "https://maven.pkg.github.com/navikt/xerces-xmlschema-1.1", "releases": { "enabled": "true" }, "snapshots": { "enabled": "false" } }]'
          servers: '[{ "id": "eresept-parent", "username": "${{ github.actor }}", "password": "${{ secrets.token }}" }, { "id": "xerces", "username": "${{ github.actor }}", "password": "${{ secrets.token }}" }]'
          output_file: snyk-settings.xml
      - name: run Snyk to test dependencies for vulnerabilities
        uses: snyk/actions/maven@9adf32b1121593767fc3c057af55b55db032dc04 #master 2022-11-29
        env:
          SNYK_TOKEN: ${{ secrets.snyk-token }}
        with:
          command: test
          args: --org=teameresept --severity-threshold=${{ inputs.threshold }} --all-projects --exclude=report -- --settings snyk-settings.xml -DskipTests -Dmdep.skip=true -Dgitlog.phase=none
      - name: Report success?
        if: success()
        env:
          SLACK_CHANNEL: ${{ inputs.channel }}
          SLACK_WEBHOOK: ${{ secrets.webhook }}
          SLACK_USERNAME: "snyk-test ${{ github.event.repository.name }}"
          SLACK_TITLE: "Snyk test of _*${{ github.event.repository.name }}*_ passed"
          SLACK_COLOR: "good"
          SLACK_ICON_EMOJI: ":snyk:"
          SLACK_FOOTER: "${{ inputs.footer }}"
          SLACK_MESSAGE: ""
          MSG_MINIMAL: true
        uses: rtCamp/action-slack-notify@e31e87e03dd19038e411e38ae27cbad084a90661 # v2
      - name: Report failure?
        if: failure()
        env:
          SLACK_CHANNEL: ${{ inputs.channel }}
          SLACK_WEBHOOK: ${{ secrets.webhook }}
          SLACK_USERNAME: "snyk-test ${{ github.event.repository.name }}"
          SLACK_TITLE: "Snyk test of _*${{ github.event.repository.name }}*_ failed"
          SLACK_COLOR: "danger"
          SLACK_ICON_EMOJI: ":snyk:"
          SLACK_FOOTER: "${{ inputs.footer }}"
          SLACK_MESSAGE: "See https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} for details"
        uses: rtCamp/action-slack-notify@e31e87e03dd19038e411e38ae27cbad084a90661 # v2
      - name: Report cancellation?
        if: cancelled()
        env:
          SLACK_CHANNEL: ${{ inputs.channel }}
          SLACK_WEBHOOK: ${{ secrets.webhook }}
          SLACK_USERNAME: "snyk-test ${{ github.event.repository.name }}"
          SLACK_TITLE: "Snyk test of _*${{ github.event.repository.name }}*_ was cancelled"
          SLACK_COLOR: "warning"
          SLACK_ICON_EMOJI: ":snyk:"
          SLACK_FOOTER: "${{ inputs.footer }}"
          SLACK_MESSAGE: ""
          MSG_MINIMAL: true
        uses: rtCamp/action-slack-notify@e31e87e03dd19038e411e38ae27cbad084a90661 # v2
